/**
 * Alle Bilddateien aus /public - erzeugt von scripts/bilder-liste.mjs.
 * Nicht von Hand ändern: Beim nächsten Build wird die Datei überschrieben.
 */
export const BILD_DATEIEN: Record<string, string[]> = {
  charaktere: [
    "/charaktere/029ED8B9-F48A-4717-8062-35097FD3E870.PNG",
    "/charaktere/046E81DC-C197-489A-A32E-3D9BE951C471.PNG",
    "/charaktere/14C75719-0C63-405B-BE59-6403F63A255C.PNG",
    "/charaktere/1D264AC4-4633-455E-9F62-0932C89A14D1.PNG",
    "/charaktere/3ACBC8A8-1244-41DD-9EDB-85116DCA8217.PNG",
    "/charaktere/6F0ADD89-4C98-4677-894E-F94F0680E234.PNG",
    "/charaktere/affentrommel.png",
    "/charaktere/affin.png",
    "/charaktere/apolloan.png",
    "/charaktere/aquana.png",
    "/charaktere/arabischerchinchi.png",
    "/charaktere/artemis.png",
    "/charaktere/BC5EF930-29F8-43AE-A4EB-81EA99644CD3.PNG",
    "/charaktere/bella.png",
    "/charaktere/bock.png",
    "/charaktere/C8A3DF7C-AD33-4819-AB14-E308C06AB145.PNG",
    "/charaktere/chat.png",
    "/charaktere/chinchi.png",
    "/charaktere/D9EA6CDF-6B54-45A5-A3B6-1AB442E2F266.PNG",
    "/charaktere/dachsatui.png",
    "/charaktere/emily.png",
    "/charaktere/evilquana.png",
    "/charaktere/fabio.png",
    "/charaktere/fan.png",
    "/charaktere/fauli.png",
    "/charaktere/FE6BADDB-B5A0-4878-B2D0-5013C5C72D6D.PNG",
    "/charaktere/geckerl.png",
    "/charaktere/h.png",
    "/charaktere/hut_alt.png",
    "/charaktere/hut.png",
    "/charaktere/jumpy.png",
    "/charaktere/knopf.png",
    "/charaktere/mikkeli.png",
    "/charaktere/pj.png",
    "/charaktere/snaefell.png",
    "/charaktere/wimpy.png",
    "/charaktere/yeti.png",
  ],
  orte: [
    "/orte/hanoi-hoan-kiem-see.png",
    "/orte/hanoi-literaturtempel.png",
    "/orte/hanoi-nachtmarkt.png",
    "/orte/hanoi-pho-bo-ga.png",
    "/orte/hanoi-train-street.png",
    "/orte/kopenhagen-hart-bageri.png",
    "/orte/kopenhagen-johns-hot-dog-deli.png",
    "/orte/kopenhagen-noma.png",
    "/orte/kopenhagen-reffen.png",
    "/orte/kopenhagen-torvehallerne.png",
    "/orte/las-vegas-bellagio.png",
    "/orte/las-vegas-ceasars-palace.png",
    "/orte/las-vegas-lukes-lobster.png",
    "/orte/las-vegas-luxor.png",
    "/orte/las-vegas-schild.png",
    "/orte/longyearbyen-brauerei.png",
    "/orte/longyearbyen-husky-cafe.png",
    "/orte/longyearbyen-stadt.png",
    "/orte/longyearbyen-supermarkt.png",
    "/orte/longyearbyen-wildnis.png",
    "/orte/new-york-broadway.png",
    "/orte/new-york-central-park.png",
    "/orte/new-york-halal-guys.png",
    "/orte/new-york-metropolitan-museum.png",
    "/orte/new-york-rockefeller-center.png",
    "/orte/nordinsel-auckland.png",
    "/orte/nordinsel-cape-reinga.png",
    "/orte/nordinsel-cathedral-cove.png",
    "/orte/nordinsel-gruender-drache.png",
    "/orte/nordinsel-heisse-quellen.png",
    "/orte/shibuya-crossing.png",
    "/orte/shibuya-family-mart.png",
    "/orte/shibuya-hachiko.png",
    "/orte/shibuya-station.png",
    "/orte/shibuya-sushiro.png",
    "/orte/shinjuku-11-eleven.png",
    "/orte/shinjuku-kabukicho.png",
    "/orte/shinjuku-kikanbo.png",
    "/orte/shinjuku-omoide-yokocho.png",
    "/orte/shinjuku-park.png",
    "/orte/venedig-bahnhof.png",
    "/orte/venedig-dal-moros.png",
    "/orte/venedig-giardini.png",
    "/orte/venedig-harry-s-bar.png",
    "/orte/venedig-markusplatz.png",
  ],
  items: [
    "/items/brille.png",
    "/items/buerste.png",
    "/items/fingerabdruckset.png",
    "/items/kamera.png",
    "/items/notizbuch.png",
    "/items/taschenlampe.png",
    "/items/veritaserum.png",
  ],
  video: [

  ],
  sonstige: [
    "/start_neu.png",
    "/start.png",
  ],
};

/** Alle Pfade am Stück - in derselben Reihenfolge wie oben. */
export const ALLE_BILDER: string[] = Object.values(BILD_DATEIEN).flat();
