/**
 * Alle Bilddateien aus /public - erzeugt von scripts/bilder-liste.mjs.
 * Nicht von Hand ändern: Beim nächsten Build wird die Datei überschrieben.
 */
export const BILD_DATEIEN: Record<string, string[]> = {
  charaktere: [
    "/charaktere/affin.png",
    "/charaktere/apolloan.png",
    "/charaktere/aquana.png",
    "/charaktere/artemis.png",
    "/charaktere/bella.png",
    "/charaktere/bock.png",
    "/charaktere/chat.png",
    "/charaktere/chinchi.png",
    "/charaktere/dachsatui.png",
    "/charaktere/emily.png",
    "/charaktere/evilquana.png",
    "/charaktere/fabio.png",
    "/charaktere/fan.png",
    "/charaktere/fauli.png",
    "/charaktere/geckerl.png",
    "/charaktere/h.png",
    "/charaktere/hut_alt.png",
    "/charaktere/hut.png",
    "/charaktere/jumpy.png",
    "/charaktere/knopf.png",
    "/charaktere/mikkeli.png",
    "/charaktere/pj.png",
    "/charaktere/snaefell.png",
    "/charaktere/wimpy.png",
    "/charaktere/yeti.png",
  ],
  orte: [
    "/orte/hanoi-hoan-kiem-see.png",
    "/orte/hanoi-literaturtempel.png",
    "/orte/hanoi-nachtmarkt.png",
    "/orte/hanoi-pho-bo-ga.png",
    "/orte/hanoi-train-street.png",
    "/orte/kopenhagen-hart-bageri.png",
    "/orte/kopenhagen-johns-hot-dog-deli.png",
    "/orte/kopenhagen-noma.png",
    "/orte/kopenhagen-reffen.png",
    "/orte/kopenhagen-torvehallerne.png",
    "/orte/las-vegas-bellagio.png",
    "/orte/las-vegas-ceasars-palace.png",
    "/orte/las-vegas-lukes-lobster.png",
    "/orte/las-vegas-luxor.png",
    "/orte/las-vegas-schild.png",
    "/orte/longyearbyen-brauerei.png",
    "/orte/longyearbyen-husky-cafe.png",
    "/orte/longyearbyen-stadt.png",
    "/orte/longyearbyen-supermarkt.png",
    "/orte/longyearbyen-wildnis.png",
    "/orte/new-york-broadway.png",
    "/orte/new-york-central-park.png",
    "/orte/new-york-halal-guys.png",
    "/orte/new-york-metropolitan-museum.png",
    "/orte/new-york-rockefeller-center.png",
    "/orte/nordinsel-auckland.png",
    "/orte/nordinsel-cape-reinga.png",
    "/orte/nordinsel-cathedral-cove.png",
    "/orte/nordinsel-gruender-drache.png",
    "/orte/nordinsel-heisse-quellen.png",
    "/orte/shibuya-crossing.png",
    "/orte/shibuya-family-mart.png",
    "/orte/shibuya-hachiko.png",
    "/orte/shibuya-station.png",
    "/orte/shibuya-sushiro.png",
    "/orte/shinjuku-11-eleven.png",
    "/orte/shinjuku-kabukicho.png",
    "/orte/shinjuku-kikanbo.png",
    "/orte/shinjuku-omoide-yokocho.png",
    "/orte/shinjuku-park.png",
    "/orte/venedig-bahnhof.png",
    "/orte/venedig-dal-moros.png",
    "/orte/venedig-giardini.png",
    "/orte/venedig-harry-s-bar.png",
    "/orte/venedig-markusplatz.png",
  ],
  items: [
    "/items/brille.png",
    "/items/buerste.png",
    "/items/kamera.png",
    "/items/notizbuch.png",
    "/items/taschenlampe.png",
  ],
  video: [

  ],
  sonstige: [
    "/start_neu.png",
    "/start.png",
  ],
};

/** Alle Pfade am Stück - in derselben Reihenfolge wie oben. */
export const ALLE_BILDER: string[] = Object.values(BILD_DATEIEN).flat();
